### PR TITLE
Now ebean packages list could contain multiple elements ([models.*,co…

### PR DESCRIPTION
**Pull request by noteax**
Fixed issue with ebean models definition parsing for expressions which creates ConfigList:

- ebean.default = ["models.*"]
- ebean.default = ["models.Order", "models.OrderItem"]
- ebean.default += "models.*"

### CODE REVIEW

**Comment by gslowikowski** [comment]
Thanks. Unfortunately this does not work. There are several problems:
- `config.getConfig( "ebean" ).resolve()` should be changed to `config.resolve().getConfig( "ebean" )`,
- there can be multiple `ebean.*` keys (e.g. `ebean.default="models.*"`, `ebean.server2="models2.*"`, `ebean.server3="models3.*"`
- values must be Java package names (directories on disk), not class names (e.g. `models.Order` is wrong value and this model will not be instrumented).

Will you improve your PR?

**Comment by gslowikowski** [comment]
Since values must be package names, do you really need this change?

**Comment by noteax** [comment]
Yep, I've reworked PR to fixed issues 1 and 2. About class names, it's not really required for my project. But I think it will be good to at least create an issue to fix it somewhen.

**Comment by gslowikowski** [comment]
New `1.0.0-beta6-SNAPSHOT` snapshot deployed. Thank you.

**Pull request merged**
