### PR TITLE
#195 - Fix build artifact final name properties resolve

### PR DESCRIPTION
**Pull request by mabrcosta**
Following up on #195, this pull request proposes a simple naive solution to the issue

### CODE REVIEW

**Comment by gslowikowski** [comment]
Hi @mabrcosta, I've already started analyzing this issue. It has to be done slightly differently.

1. this new parameter shouldn't have `property` attribute, changing it's default value will not work
2. since it's read-only, it should be hidden, no javadoc needed
```
    @Parameter( defaultValue = "${project.build.finalName}", readonly = true)
    private String finalName;
```

It should be used in two places, the second one is in `projectAttachedArtifactFileName` variable initialization below.

Can you implement these changes?

**Comment by mabrcosta** [comment]
Hi @gslowikowski. I've implemented the changes you mentioned and updated the pull request.

Thanks for quickly analysing the issue.

**Comment by gslowikowski** [comment]
Thank you @mabrcosta

**Comment by froque** [comment]
@gslowikowski can we get a stable release (non SNAPSHOT) with this please ?

**Pull request merged**
